[package]
name = "create-context"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
walkdir = "2"
glob = "0.3"
ignore = "0.4.23"
rayon = "1.10.0"
tiktoken-rs = "0.6.0"
